
services:

  api:
    build: .
    env_file: docker-compose.env
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    restart: always
    networks:
      - internal

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - internal

networks:
  internal:

volumes:
  mysql_data:
