### Register
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "username": "johndoe",
  "email": "johndoe@gmail.com",
  "password": "johndoe123"
}


### Log In 1
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "janedoe@gmail.com",
  "password": "jane123doe"
}

### Log In 2
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "johndoe@gmail.com",
  "password": "johndoe123"
}

### Log Out
POST http://localhost:4000/api/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1NjE4NDMwLCJleHAiOjE3NTU3MDQ4MzB9.-hkQaHMt3WCo9ZaW-x1_ErwCK0mjX7F8STFLkclAoRo

### Create Room
POST http://localhost:4000/api/rooms/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU1NzQyMzc0LCJleHAiOjE3NTU4Mjg3NzR9.0FViGkvNrSHim7hNmU81hYQJ8GL_ulBT4Gcr2wFbzEg
Content-Type: application/json

{
  "name": "General Chat",
  "description": "A room for general discussions",
  "isPublic": true
}

### Join Room
POST http://localhost:4000/api/rooms/join HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1NzQxMDQ3LCJleHAiOjE3NTU4Mjc0NDd9.SmqAXCM3DALU5ZMZHP2JPI4S3HLZ4mgcEv4molPF7E8
Content-Type: application/json

{
  "roomId": 2,
  "inviteCode": "X0ESZN6F"
}

### My Rooms
GET http://localhost:4000/api/rooms/my-rooms HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1NzQxMDQ3LCJleHAiOjE3NTU4Mjc0NDd9.SmqAXCM3DALU5ZMZHP2JPI4S3HLZ4mgcEv4molPF7E8

### Get Messages
GET http://localhost:4000/api/rooms/1/messages HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1NzQxMDQ3LCJleHAiOjE3NTU4Mjc0NDd9.SmqAXCM3DALU5ZMZHP2JPI4S3HLZ4mgcEv4molPF7E8
